# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c891391458adf7a8775f78ce1931d2d54137b9b6a49b65ff6ba854b88de7cce3f0d5001a6addc7ca8b0afa962911a413a8b3c0160551c65f1d805e5d0180d7e8

test:
  secret_key_base: efbc4fe4481a31366f81a4462ff9b4b2078a200bb6eae00035da2eb03c2ffdcf10ef12a024dcbbcb8f6a60a9171dab71a44a67bcf3bd8e486c3256909ac4998c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
